[tool.poetry]
name = "optimization"
version = "0.1.0"
description = "A slist of common optimisation problems"
authors = ["marcodigennaro <m.di.gennaro@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
